{% set name = "pacmap" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pacmap-{{ version }}.tar.gz
  sha256: fad1ce6cc5ecaccfdbdd16522692a5b45f2f3d7af32fc77c47571b435012ad1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - scikit-learn >=0.20
    - numba >=0.57
    - python-annoy >=1.11
    - numpy >=1.20

test:
  imports:
    - pacmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/YingfanWang/PaCMAP
  summary: 'The official implementation for PaCMAP: Pairwise Controlled Manifold Approximation Projection'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hyhuang00
